     - ./html_other:/var/www/html
    restart: always 
    networks:
      - proxy_net



  mariadb_other:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE_1=wordpress_other
     - VIRTUAL_HOST=other.data-ops.info
    depends_on:
     - nginx-proxy
     - letsencrypt    
    volumes:
     - ./database_other:/var/lib/mysql
    restart: always 
    networks:
      - proxy_net





#-----------------------------------------------------  
  default:
    image: mikeq/hello-world:latest
    container_name: www
    depends_on:
      - nginx-proxy
      - letsencrypt
    environment:
      - VIRTUAL_HOST=data-ops.info,www.data-ops.info
    networks:
      - proxy_net
#----------------------------------------------------- 
networks:
  cert_net:
    driver: bridge
  proxy_net:
    driver: bridge
